### ISSUE TITLE
Async modules

### ISSUE THREAD

**Issue by qur2** [liamcmitchell/url-io#2]
Hi,

I'm thinking about lazy loading a module so that webpack splits my bundle and the module is loaded on demand, not eagerly.
Something naive like that:

```
createIO({
  /module': (request) => {
    System.import('module/source').then((handler) => handler(request))
  },
})
```

Right now, I'm under the impression that only the handlers themselves are asynchronous, but the whole path resolving mechanism does not handle promises at all.

At the moment, the only way I see to handle code splitting is to actually have a very thin IO configuration and all its handler starting with a `System.import()`.
That way, the IO stuff is loaded eagerly (but should be very thin) and the (hopefully) heaviest parts can still be lazy loaded.
However, this is not very efficient as the module has to be written specifically to handle code splitting.

Do I understand correctly? Do you have a better way of approaching code splitting? Does `url-io` require modification to support that?

Thank you.

**Comment by liamcmitchell** [comment]
Thanks, asyncSource helper added in https://github.com/liamcmitchell/url-io/commit/90841279d1cca41b4dd6b25a4468fa3fb9d39f2e

Usage with webpack lazy loading:
```
import {createIO, paths, asyncSource} from 'url-io'

export default createIO(paths({
  '/lazy': asyncSource(() => import('./lazySource').then(m => m.default)),
}))
```

**Comment by qur2** [comment]
Awesome, thanks!
